# Generated by Django 3.1.2 on 2020-10-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0002_auto_20201012_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
