# Generated by Django 3.1.2 on 2020-10-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0003_remove_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=False, upload_to='image/'),
            preserve_default=False,
        ),
    ]
