# Generated by Django 3.1.2 on 2020-10-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0005_auto_20201013_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
