# Generated by Django 3.1.2 on 2020-10-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin_side', '0006_auto_20201015_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='image/')),
                ('price', models.PositiveIntegerField()),
                ('desc', models.TextField(max_length=1000)),
                ('available', models.BooleanField(default=False)),
                ('genre', models.ManyToManyField(to='Admin_side.Genre')),
            ],
        ),
    ]
