# Generated by Django 3.1.2 on 2020-10-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
