# Generated by Django 3.1.2 on 2020-10-16 14:52

import User_side.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0007_book_genre'),
        ('User_side', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_to_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(to='Admin_side.Book')),
                ('owner', models.ForeignKey(on_delete=User_side.models.Subscriber, to='User_side.subscriber')),
            ],
        ),
    ]
